# Generated by Django 4.2.4 on 2023-08-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0002_lesson_student_lessonnote_lesson_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="is_trial",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="location",
            field=models.CharField(default="WPMA", max_length=500),
        ),
    ]
