# Generated by Django 4.2.4 on 2023-09-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0004_semester_alter_lesson_student_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("reminder_text", models.TextField()),
                ("dismissed", models.BooleanField(db_index=True, default=False)),
                ("dismissed_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
